FROM mcr.microsoft.com/dotnet/aspnet:6.0.2-bullseye-slim-arm32v7
ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

COPY ScopeWebApi/bin/Release/net6.0/publish /webapp
WORKDIR /webapp
ENTRYPOINT ["dotnet","ScopeWebApi.dll", "--urls", "http://*:5000"]

