version: "3.1"
services:
  pipico:
    container_name: ScopeWebApi
    image: "192.168.1.125:5000/scopewebapi:latest"
    ports:
      - "5000:5000"
    volumes:
      - "/media/tracefiles:/media/tracefiles"
    environment:
      - TraceFilesPath=/media/tracefiles
    #restart: always
