version: "3.1"
services:
  picoservices:
    image: "192.168.1.125:5000/irtransmitterapi:latest"
    ports:
      - "5000:5000"
#    volumes:
#      - "/media/Music:/media/mp3"
#    environment:
#      - MP3Player=mpg123
    #restart: always
