version: "3.1"
services:
  picoservices:
    image: "192.168.1.125:5000/irtransmitterapi:latest"
    ports:
      - "5000:5000"
    volumes:
      - "/home/pi/Documents:/data"
    environment:
      - DatabasePath=/data/ir.dat
      - LogFilePath=/data/ir.log
    #restart: always
