version: "3.1"
services:
  pipico:
    container_name: IRTransmitterApi
    image: "192.168.1.125:5000/irtransmitterapi:latest"
    ports:
      - "5001:5000"
    volumes:
      - "/media/database:/media/database"
      - "/media/logs:/media/logs"
    environment:
      - DatabasePath=/media/database/irtransmitterapi.sql
      - LogFilePath=/media/logs/irtransmitterapi.log
    #restart: always
