version: "3.1"
services:
  pipico:
    container_name: PicoServices
    image: "192.168.1.125:5000/picoservices:latest"
    ports:
      - "5000:5000"
    #volumes:
    #  - "/media/database:/media/database"
    #  - "/media/logs:/media/logs"
    #environment:
    #  - DatabasePath=/media/database/music.sql
    #  - DatabaseUpdateLogFile=/media/database/musicupdates.sql
    #  - LogFilePath=/media/logs/jbdbapi.log
    #  - ErrorLogFilePath=/media/logs/jbdbapierrors.log
    #restart: always
